// Vode Plugins — Sectra Scope: versioning / company info.

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake (smtg_target_configure_version_file).
#include "projectversion.h"

#define stringOriginalFilename "sectrascope.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Sectra Scope VST3 (64Bit)"
#else
#define stringFileDescription "Sectra Scope VST3"
#endif
#define stringCompanyWeb     "https://vode.example.com"
#define stringCompanyEmail   "mailto:plugins@vode.example.com"
#define stringCompanyName    "Vode Plugins"
#define stringLegalCopyright "(c) 2026 Vode Plugins"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
