// Vode Plugins — passthrough: versioning / company info.

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake (smtg_target_configure_version_file).
#include "projectversion.h"

#define stringOriginalFilename "passthrough.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Vode Passthrough VST3 (64Bit)"
#else
#define stringFileDescription "Vode Passthrough VST3"
#endif
#define stringCompanyWeb     "https://vode.example.com"
#define stringCompanyEmail   "mailto:plugins@vode.example.com"
#define stringCompanyName    "Vode Plugins"
#define stringLegalCopyright "© 2026 Vode Plugins"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
